### ISSUE TITLE
Upstreaming?

### ISSUE THREAD

**Issue by Disasm** [xobs/vexriscv-rust#1]
Hi!
Have you considered upstreaming the changes to `riscv`? I think that VexRiscv-specific registers could live there under the corresponding feature gate.

**Comment by xobs** [comment]
Yes, that could work.

Originally I forked it to remove symbols we weren't using, in order to reduce binary size.  However, with lto, that doesn't seem necessary, so upstreaming makes more sense now.

**Comment by Disasm** [comment]
I believe this should work even without LTO: all the assembly functions reside in their own sections and Rust already does a great job removing unused code.
Anyway, I'm quite interested in moving the rust-litex-vexriscv ecosystem forward. Unfortunately, I'm working on this in my free time, so my performance is not that great and any help is highly appreciated.

**Comment by xobs** [comment]
I'll post a deprecation notice once the `riscv` crate version gets bumped and we can replace "vexriscv" with "riscv" in various projects.

**Comment by Disasm** [comment]
Published v0.5.6

**Comment by xobs** [comment]
Thanks!

**Comment by phansel** [comment]
at this point, does that mean this crate is deprecated?
