### ISSUE TITLE
Moving vexriscv-specific registers back to the vexriscv crate

### ISSUE THREAD

**Issue by Disasm** [xobs/vexriscv-rust#2]
Hi @xobs! Sorry for bothering you again. In https://github.com/xobs/vexriscv-rust/issues/1 I asked about upstreaming the changes you made in this crate. I followed with https://github.com/rust-embedded/riscv-rt/pull/45 and then you added vexriscv-specific registers in https://github.com/rust-embedded/riscv/pull/37.

However, since then things have changed a bit. While working with the Nuclei core used in GD32VF103 chips, we realized that some CSRs, despite having standard names, can be incompatible with the RISC-V spec. If we had to port these Nuclei registers to the `riscv` crate, such nuances would be difficult to take into account without producing a difficult-to-support feature-gate mess everywhere. So we decided that it's better to keep Nuclei-specific registers (as well as their modified "standard" CSRs) in a separate crate and use the `riscv` crate for standard CSRs that are defined in the Spec.
As a side-product of this decision we decided to also keep all the vexriscv-specific registers in a separate crate, partly because some of the folks expressed concern about our decision to move these registers to the `riscv` crate. There is a PR (https://github.com/rust-embedded/riscv/pull/48) that reflects this decision, but I'd like to discuss it with you first.
My original idea was to avoid code duplication in `riscv` and `vexriscv` crates by having a single source of code for the standard registers. However, we can still achieve this by using `riscv` for RISC-V-standard registers and using `vexriscv` for all the vexriscv-specific ones. So my proposition is to remove all the vexriscv-specific CSRs from the `riscv` crate **and** remove all the standard CSRs from the `vexriscv` crate.
What do you think about this? If it works for you, I can follow with a PR to this repo.

**Comment by xobs** [comment]
That works for me.

That does make sense, and is probably the best solution considering the landscape of RISC-V CSRs. Especially since on VexRiscv, these things are customisable, so it's not out of the realm of possibility to have the custom CSRs change what CSR number they use.
